[package]
name = "editeuren"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
libc = "0.2.119"
nix = "0.23.1"
termios = "0.3.3"
